### ISSUE TITLE
The url of the request is not complete when grouping routes

### ISSUE THREAD

**Issue by imikodanic** [Treblle/treblle-express#2]
So pretty much when using the express' router.use method the Treblle SDK doesn't recognize the prefixes. It recognizes only the "route" which was defined in the e.g. router.post()

THIS WILL BE IGNORED:
`router.use("/user", routerObject)`

THIS WILL BE SHOWN:
`router.post("/follow", someController)`

I think the problem is when creating the request payload in the SDK you only fetch the request's url by doing `req.url`.
We should try and find a way to get the whole URL.

**Comment by DominusKelvin** [comment]
Thanks @Mikodanic-I 

I'm publish a new version which will resolve this.

**Comment by DominusKelvin** [comment]
Hey @Mikodanic-I I just release v0.0.5 to fix this.

Thanks for catching it.
