### ISSUE TITLE
Request never sent to Treblle

### ISSUE THREAD

**Issue by lsantiagond** [Treblle/treblle-express#7]
### Problem Description
I attempted to integrate @treblle/express into my API following the documentation, but the requests are not being sent to Treblle’s servers. After some investigation comparing the code of version 1.0.0 with the previous version (0.0.8) it seems there is an issue with the logic on line 44 of treblleMiddleware.

```js
if (!isPathBlocked) {
  return next()
}
```

This condition prevents the rest of the code from executing, even when blocklistPaths is empty. After commenting out this line, the requests started working correctly and were sent to Treblle.

### Expected Behavior
If blocklistPaths is empty or does not include req.path, the logic for sending requests to Treblle should execute.

### Current Behavior
The !isPathBlocked condition prematurely stops execution, preventing requests from being sent to Treblle.

### PD
I manually patched that line removing the negation and now everything works as expected

### Environment
- @treblle/express  v1.0.0
- Express v4.17.1
- Node.js v20.9.0
- Ubuntu 24

**Comment by nikme** [comment]
Hi, I have pushed new update so solve this. v1.0.1
Thank you for the report
